sudo: required

language: python
python: '2.7'

env:
  - docker: 1
    dockerfile_name: Dockerfile.py3
    docker_tag_suffix: dev-py3

install: true

services:
  - docker

script:
  - if [ -n "$docker" ]; then sudo ./travis/docker.sh ; fi;

notifications:
  slack:
    rooms:
      secure: nPY+SvgkOrpvU76i55bDtXPbclq7WzY2DCwOCbYNzpMMTNnlqV9uhwUc31gHdl+xO8aXf52JwuOqTZnJTi9PGuomp7qf4N4z/dz3tKdjj3ppgeDx8hcmAikiM/qoOUadA9zNvP+wHfJSK7l6LnbAZgdOAXZb77Fk5rIuRr695vg=
    on_success: always
    on_failure: always
    on_start: always
